#!/usr/bin/env node
const fs = require('node:fs');

// armor pieces to generate
let armor_pieces = ["helmet", "chestplate", "leggings", "boots"]
// armor materials to generate the trims on, under the form [namespace, material, has_overlay]
let armor_materials = [["minecraft", "leather", true], ["matcha", "sturdy_leather", [true, false, true, false]], ["minecraft", "copper"], ["minecraft", "chainmail"], ["minecraft", "iron"], ["minecraft", "golden"], ["minecraft", "diamond"], ["minecraft", "netherite"], ["matcha", "steel"], ["matcha", "shakudo"], ["matcha", "electrum"], ["matcha", "bronze"], ["minecraft", "turtle"]]
// trims to generate, under the form [namespace, material]
let trim_materials = [["matcha", "silver"], ["matcha", "electrum"], ["matcha", "bronze"], ["matcha", "shakudo"], ["matcha", "steel"], ["minecraft", "amethyst"], ["minecraft", "copper"], ["minecraft", "diamond"], ["minecraft", "emerald"], ["minecraft", "gold"], ["minecraft", "iron"], ["minecraft", "lapis"], ["minecraft", "netherite"], ["minecraft", "quartz"], ["minecraft", "redstone"], ["minecraft", "resin"]]



for (const p of armor_pieces) {
  for (const material of armor_materials) {
    let m_namespace = material[0]
    let m = material[1]
    let has_overlay = false
    let has_tint = false

    // complex check for armor set that have overlay on all armor or on specific armor pieces
    if (material.length > 2) {
      if (typeof material[2] == "object") {
        has_tint = true
        switch (p) {
          case "helmet":
            has_overlay = material[2][0]
            break;
          case "chestplate":
            has_overlay = material[2][1]
            break;
          case "leggings":
            has_overlay = material[2][2]
            break;
          case "boots":
            has_overlay = material[2][3]
            break;
        }
      } else if (typeof material[2] == "boolean"){
        has_overlay = material[2]
        has_tint = true
      }
    }

    // for turtle armor, we only do the helmet
    if (m == "turtle" && p != "helmet") break;

    // file to write the item definition in
    // SHOULD be in the correct namespace (but isn't for compatibility here)
    // (please klei, I know it would break a lot of things, but having everything in "minecraft" is a pain T_T)
    let items_name = "assets/" + "minecraft" + "/items/" + m + "_" + p + ".json"
    let items_content = {
      "model": {
        "type": "minecraft:select",
        "cases": [],
        "fallback": {
          "type": "minecraft:model",
          "model": m_namespace + ":item/" + m + "_" + p
        },
        "property": "minecraft:trim_material"
      }
    }
    // if the item has an overlay, color it (default is leather color)
    if (has_tint) {
      items_content.model.fallback["tints"] = [
          {
            "type": "minecraft:dye",
            "default": -6265536
          }
        ]
    }

    // no need to overwrite default minecraft models
    if (m_namespace != "minecraft") {
      //generate the default model of the item
      let item_trimless = {
        "parent": "minecraft:item/generated",
        "textures": {
          "layer0": m_namespace + ":item/" + m + "_" + p
        }
      }
      if (has_overlay) {
        item_trimless.textures["layer1"] = m_namespace + ":item/" + m + "_" + p + "_overlay"
      }
      fs.writeFile("assets/" + m_namespace + "/models/item/" + m + "_" + p + ".json", JSON.stringify(item_trimless, null, 2), err => {})
    }

    // add EVERY trim material one by one
    for (const trim of trim_materials) {
      let t = trim[1]
      let t_namespace = trim[0]

      // don't re create the vanilla models
      if (t_namespace != "minecraft" || m_namespace != "minecraft") {
        let item_model_name = "assets/" + m_namespace + "/models/item/" + m + "_" + p + "_" + t + "_trim.json"
        // base of this trim model
        let item_model_content = {
          "parent": "minecraft:item/generated",
          "textures": {
            "layer0": m_namespace + ":item/" + m + "_" + p,
          }
        }
        // add the autogenerated trim (and potential overlay) to the model
        if (has_overlay) {
          item_model_content.textures["layer1"] = m_namespace + ":item/" + m + "_" + p + "_overlay"
          item_model_content.textures["layer2"] = "minecraft:trims/items/" + p + "_trim_" + t
        } else {
          item_model_content.textures["layer1"] = "minecraft:trims/items/" + p + "_trim_" + t
        }
        // if the trim and armor are of the same material, make the trim darker (yes golden armor is not gold armor for some reason...)
        if (m == t || (m == "golden" && t == "gold")) {
          item_model_content.textures.layer1 += "_darker"
        }
        // write the model
        fs.writeFile(item_model_name, JSON.stringify(item_model_content, null, 2), err => {})
      }

      // add the newly created file (or default minecraft one) to the list to choose from in the item definition
      let a = {
        "model": {
          "type": "minecraft:model",
          "model": m_namespace + ":item/"+ m + "_" + p + "_" + t + "_trim"
        },
        "when": t_namespace + ":" + t
      }
      // tint the leather armor
      if (has_tint) {
        a.model["tints"] = [
            {
              "type": "minecraft:dye",
              "default": -6265536
            }
          ]
      }
      items_content.model.cases.push(a)
    }
    fs.writeFile(items_name, JSON.stringify(items_content, null, 2), err => {})
  }
}
